# Site settings
title: Associazione Italiana Studenti di Fisica
description: Sito in costruzione, un po' di pazienza
banner: img/banner.png
# url: "http://yourdomain.com" # the base hostname & protocol for your site
destination: ../site/
locale: "it"

# Build settings
markdown: kramdown
future: true
permalink: /blog/:year/:month/:day/:title/

#facebook
fb_admins: 
fb_appid:

#Collections
collections:
  events:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

gems:
 - jekyll-redirect-from
 - jekyll-sitemap
